### Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [16]:
import numpy as np

In [18]:
def vandermonde(l,n,increase = False):
    if increase:
        print(np.array([j**i for j in l for i in range(n)]).reshape(len(l),n))
    else:
        print(np.array([j**(n-1-i) for j in l for i in range(n)]).reshape(len(l),n))

l1 = [2,3,4]
n = 4
print('decrease')
vandermonde(np.array(l1),n)
print()
print('increase')
vandermonde(np.array(l1),n,increase = True)

decrease
[[ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]

increase
[[ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


### Problem Statement 2:
- Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
- The moving average sequence has n-k+1 elements as shown below.
- The moving averages with k=4 of a ten-value sequence (n=10) is shown below
- i 1 2 3 4 5 6 7 8 9 10
- ===== == == == == == == == == == ==
- Input 10 20 30 40 50 60 70 80 90 100
- y1 25 = (10+20+30+40)/4
- y2 35 = (20+30+40+50)/4
- y3 45 = (30+40+50+60)/4
- y4 55 = (40+50+60+70)/4
- y5 65 = (50+60+70+80)/4
- y6 75 = (60+70+80+90)/4
- y7 85 = (70+80+90+100)/4
- Thus, the moving average sequence has n-k+1=10-4+1=7 values.

### Question: Write a function to find moving average in an array over a window:
### Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [19]:
def moving_avg(arr,k):
    y = [ ]
    for i in range(len(arr)):
        sum = 0 
        for j in range(i,i+k):
            if j < len(arr)-k+1:
                sum = sum+arr[j]
        y.append(sum/k)
    for i in range(0,len(arr) - k + 1):
        print(round(y[i],2))

arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = int(input('enter the value of window'))
print(moving_avg(arr,k))

enter the value of window3
5.0
4.67
5.67
6.67
9.67
28.67
49.33
72.67
84.0
60.0
33.0
None
